version: '3.8'

services:
  mongo:
    image: mongo:5.0.9-focal
    ports:
      - 27017:27017
    networks:
      - mongo
    volumes:
      - .data:/data/db

  redis:
    image: redis:7.0.0-alpine
    ports:
      - 6379:6379
    networks:
      - redis

  cpc-scrapper:
    image: juanpablotyrlik/microservices-app-cpc-scrapper
    depends_on:
      - redis
    networks:
      - redis
    deploy:
      replicas: 1

  redis-to-mongo:
    image: juanpablotyrlik/microservices-app-redis-to-mongo
    depends_on:
      - redis
      - mongo
    networks:
      - redis
      - mongo
    deploy:
      replicas: 1

  api:
    image: juanpablotyrlik/microservices-app-api
    depends_on:
      - mongo
    networks:
      - mongo
      - proxy
    deploy:
      replicas: 1

  frontend:
    image: juanpablotyrlik/microservices-app-frontend
    depends_on:
      - api
    networks:
      - proxy

  nginx:
    image: juanpablotyrlik/microservices-app-nginx
    ports:
      - 80:80
    networks:
      - proxy
    depends_on:
      - api
      - frontend

networks:
  mongo:
    driver: overlay
  redis:
    driver: overlay
  proxy:
    driver: overlay

volumes:
  .data: