version: '3.8'

services:
  mongo:
    image: mongo:5.0.9-focal
    ports:
      - 27017:27017
    networks:
      - mongo
    volumes:
      - .data:/data/db

  redis:
    image: redis:7.0.0-alpine
    ports:
      - 6379:6379
    networks:
      - redis

  cpc-scrapper:
    image: juanpablotyrlik/microservices-app-cpc-scrapper
    depends_on:
      - redis
    networks:
      - redis
    deploy:
      replicas: 3

  redis-to-mongo:
    image: juanpablotyrlik/microservices-app-redis-to-mongo
    depends_on:
      - redis
      - mongo
    networks:
      - redis
      - mongo
    deploy:
      replicas: 3
  api:
    image: juanpablotyrlik/microservices-app-api
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - mongo
    deploy:
      replicas: 3
networks:
  mongo:
    driver: overlay
  redis:
    driver: overlay

volumes:
  .data: